package com.kenai.dao;

import com.kenai.dataobject.ItemDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 17 19:29:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 17 19:29:27 CST 2020
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 17 19:29:27 CST 2020
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 17 19:29:27 CST 2020
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * 根据销量降序查询所有商品
     * @return
     */
    List<ItemDO> listItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 17 19:29:27 CST 2020
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 17 19:29:27 CST 2020
     */
    int updateByPrimaryKey(ItemDO record);

    /**
     * 销量增加
     * @param id
     * @param amount
     * @return
     */
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}